### ISSUE TITLE
bugs in estimating LAI in Noah-MP

### ISSUE THREAD

**Issue by WanshuNie** [NASA-LIS/LISF#227]
In Noah-MP, we found that LAI is estimated as a function of days of the year and the look up vegetation parameter table when dynamic vegetation is turned off. It is not linked to GVF input so that there is no interannual variability in LAI output.

In Noah-MP, the related piece of code is found at module_sf_noahmplsm_36.F90:

   LAI = WT1* LAIM(VEGTYP,IT1) + WT2* LAIM(VEGTYP,IT2)

While in Noah models, we found that LAI is estimated as a function of GVF in noah36_setvegparms.F90

           if(noah36_struc(n)%noah(t)%shdmax.gt.noah36_struc(n)%noah(t)%shdmin) then
              interp_fraction =                                        &
                   (noah36_struc(n)%noah(t)%shdfac-noah36_struc(n)%noah(t)%shdmin) / &
                   (noah36_struc(n)%noah(t)%shdmax-noah36_struc(n)%noah(t)%shdmin)
              interp_fraction = min(interp_fraction,1.0)
              interp_fraction = max(interp_fraction,0.0)

              if(LIS_rc%uselaimap(n).eq."none") then ! no map specified
                 noah36_struc(n)%noah(t)%lai = ((1.0-interp_fraction) * &
                      noah36_struc(n)%laimin(noah36_struc(n)%noah(t)%vegt) + &
                      interp_fraction*noah36_struc(n)%laimax(noah36_struc(n)%noah(t)%vegt))

 This bug was found when Cristina was looking at the LAI output from her Noah-MP simulation for South America.

**Comment by dmocko** [comment]
Hi Wanshu,

I'm leaving this up as an issue for now, but I think this is really a function of how Noah and Noah-MP LSMs are constructed.

Our overall philosophy when implementing an LSM into LIS is that we don't change any of the physics or how it runs.  The LSM should run the same and produce the same output when run in LIS or when run outside of LIS.  We benchmark our output this way, and don't consider the LSM to be properly implemented in LIS until the outputs are identical.

We did indeed do this for all versions of Noah and Noah-MP available in LIS.

If you look at the LIS Users's Guide, you will see that there are 4 vegetation options with Noah-MP-3.6.  One is for running dynamic vegetation turned "on"; the other three only use table LAI.

Noah-MP-4.0.1 was recently implemented into LIS as well.  This version of Noah-MP has additional vegetation options, that include using input LAI (from the LDT lis_input file) instead of from the look-up table.  If you had an interannually-varying LAI dataset, then you could use one of these options with Noah-MP-4.0.1 LSM.

David

**Comment by WanshuNie** [comment]
Hi David,

I see. Thank you for the explanation and that makes sense to me. I think we will either create a customized version of Noah-MP.3.6 or switch to version 4.0.1.

Best,
Wanshu

**Comment by dmocko** [comment]
Closing this issue, as it is not a problem of the code - just differences in how Noah and Noah-MP handle LAI.
