### ISSUE TITLE
Feature: Implement rotated-pole coordinate support in LDT and LIS

### ISSUE THREAD

**Issue by karsenau** [NASA-LIS/LISF#247]
Request to implement a scheme or computations that would allow for rotated lat-lon grid coordinates (e.g., for winds).

**Comment by dmocko** [comment]
Are "rotated-pole coordinate"s supported by NU-WRF?

**Comment by karsenau** [comment]
Most likely, as WRF can typically writes out wind components on rotated grids (such as https://www-k12.atmos.washington.edu/~ovens/wrfwinds.html)

This is a request from some users to be able to put some fields on rotated-pole grids

**Comment by emkemp** [comment]
(Apologies for late response)

This is complicated.  The WPS map projection library included in NU-WRF does include rotated poles, since some GRIB data exists with this projection.  (That's probably what is relevant to Kristi's question.)

The NMM version of WRF (now retired) can run with this projection.  NOAA modified the ARW version of WRF to also run with this projection (this is RAP and HRRR), but I don't believe these changes were backported to the community ARW.  And since NU-WRF is based on the community ARW, I don't believe NU-WRF will run with that projection. Which means if you wanted to allow LIS to run in rotated lat/lon projection, you could not support NU-WRF coupling for that projection.

**Comment by karsenau** [comment]
Thanks, Eric, for your inputs on the NUWRF coupling aspect in relation to this feature request.

I have been thinking about how to best support this feature.  I didn't know if we could support in LIS output fields having two projections written out within the same file (e.g., main output fields in latlon, and certain fields in the rotated grid) and having information about both grids within the same file. 

I don't see a problem at least supporting the rotated pole coordinates in LDT/LIS/LVT, but I guess we will have those exceptions, such as coupling with NUWRF, that we will have to document for users.

Just a couple of other useful links for CF compliance and one application (via ECMWF):
http://cfconventions.org/Data/cf-conventions/cf-conventions-1.0/build/ch05s06.html
(example 5.6 section)
https://apps.ecmwf.int/codes/grib/format/grib1/grids/10/

Also, NCL plotting example:
https://www.ncl.ucar.edu/Applications/rotatedltln.shtml

**Comment by dmocko** [comment]
Boosting this issue, as users of the UM need LIS to be able to support rotated lat-lon grids in LDT and LIS.
