### ISSUE TITLE
Incomplete documentation for the irrigation code

### ISSUE THREAD

**Issue by sujayvkumar** [NASA-LIS/LISF#511]
There are several new irrigation options which are not included in the master lis.config 

Irrigation GVF parameter 1:
Irrigation GVF parameter 2:

These config options are not intuitive - Please come up with better config entries for these  (minimum threshold, maximum threshold etc.)

**Comment by sujayvkumar** [comment]
The following log statement in noahmp36_getirrigationstates.F90 should be disabled (it  inundates the LIS log file when irrigation does not occur)

**Comment by sujayvkumar** [comment]
! If we are outside of the irrigation window, set rate to 0
     if ((ltime.gt.shift_otimee).or.(ltime.lt.shift_otimes)) then
       irrigRate(t) = 0.0
       write(LIS_logunit,*) '[INFO] ',ltime, &
            'is outside the irrigation window'     
     endif

**Comment by jerlingi** [comment]
Hi Sujay,

Sorry about the stray comment making it in to the final version! in SRC/lis/configs/lis.config.adoc, I had included a brief description of these parameters:

`Irrigation GVF parameter 1:` specifies growing season for
irrigation in Noah-MP (set to 0.40 for Noah 3.3 irrigation)

`Irrigation GVF parameter 2:` specifies growing season for
irrigation in Noah-MP (set to 0.00 for Noah 3.3 irrigation)

I agree that they need a better description, but should they be also somewhere else too?

**Comment by karsenau** [comment]
I think we could provide more specifically what the two parameters represent and the source for this update to the original work implemented by Mutlu and Hiroko.

Here is some additional information that we could pull from and provide more background on these two parameters in the lis.config.adoc file.  

In the original GVF threshold of the sprinkler irrigation scheme by Ozdogan et al. (2010), a fraction 0.4 was applied as part of the max-min seasonality in GVF.  Then from Wanshu, in her Nie et al. (2018) paper, she modified that constant fraction value when applied the dynamic GVF option.  Wanshu: "Instead of using 0.4, we use two parameters and the GVF range to adjust the percentage of cut-off, so that areas of greater GVF range will have a higher percentage cut-off and areas of lower GVF range will have a lower cut-off, we found this is helpful to improve the simulated irrigation amount under drought conditions for High Plains. On the other hand, the model is more flexible, since the two parameters (GVFparam1 and GVFparam2) can be adjusted accordingly, if prior information of growing season is available. We can also set GVFparam1=0.4, GVFparam2=0 to go back to the original setting in Ozdogan et al. (2010)."

Wanshu: "Thus, We are trying to use "(LIS_rc%irrigation_GVFparam1 + LIS_rc%irrigation_GVFparam2*(shdmax-shdmin))” to substitute a constant value of 0.4. Let’s say the 0.4 means that 40% cut-off for the threshold. By using the new equation, we are able to adjust this cut-off percentage as a function of the GVF range (shdmax - shdmin), so that irrigation will be triggered at for example 60% for the grid cell with higher GVF range while may be less than 40% for the grid cell with lower GVF range."

**Comment by jerlingi** [comment]
@karsenau, that's a great summary! 

I modified it to read 

In the original GVF threshold in the sprinkler irrigation scheme by Ozdogan et al. (2010),
a fraction of 0.4 was applied as part of the max-min seasonality in GVF. Nie et al. (2018)
added a dyanmic option. These two parameters and the GVF range allow the user to adjust
the percentage of the irrigation cut-off so that areas of greater GVF range will have a
higher percentage cut-off and areas of lower GVF range will have a lower cut-off. In the
code, the irrigation threhold contains the term
(GVFparam1 + GVFparam2*(shdmax-shdmin))
instead of a static value of 0.4. By using this equation, the user may adjust the cut-off
percentage as a function of GVF range (shdmax-shdmin).

and will issue a pull request for these fixes.
