### ISSUE TITLE
LVT Cannot compile: Symbol has no implicit type

### ISSUE THREAD

**Issue by rfun** [NASA-LIS/LISF#578]
Hi Devs, 

I am trying to compile LVT (I have LDT and LIS compile just fine) and am using the mpicc and mpif90 compilers for this. I got past the huge module compilation for LDT by using a beefier machine and setting optimization level to 0. However, I am stuck at the following error, as I am not very familiar with fortran. 

`Compiling LVT

[INFO] Compiling LVT source code

/usr/bin/mpif90 -c -pass-exit-codes -ffree-line-length-0 -O0  -fbacktrace  -fconvert=big-endian -DHIDE_SHR_MSG -DNO_SHR_VMATH -DGFORTRAN -DHIDE_MPI -I/sandbox/esmf/install/mod  -I/usr/local/include/ -I/sandbox/netcdf-c/4.7.3/install/include/  -I/usr/local/include/  -I/usr/local/include/  -I./ -I../core/ ../datastreams/SMAPTB/readSMAPTBobs.F90
../datastreams/SMAPTB/readSMAPTBobs.F90:351:9:

  351 |      do c=1,LVT_rc%lnc
      |         1
Error: Symbol 'c' at (1) has no IMPLICIT type
../datastreams/SMAPTB/readSMAPTBobs.F90:350:6:

  350 |   do r=1,LVT_rc%lnr
      |      1
Error: Symbol 'r' at (1) has no IMPLICIT type
make: *** [Makefile:108: readSMAPTBobs.o] Error 1

[ERR] Compile failed
`
I've attached my configure.lvt file as well. As far as my understanding goes, this is an issue with the fortran code and maybe some of the right header files are missing, but it could also be an issue with my environment.

Any help is appreciated. 

[configure.lvt.txt](https://github.com/NASA-LIS/LISF/files/5152300/configure.lvt.txt)

**Comment by bmcandr** [comment]
Hi @rfun 👋 ,

Thanks opening this issue! It looks like this error is due to the variables `r` and `c` being defined within an *if* block that begins [at line 134](https://github.com/NASA-LIS/LISF/blob/f05554b117639b731525d289f7be568daa9d9288/lvt/datastreams/SMAPTB/readSMAPTBobs.F90#L134) (`#if (defined USE_HDF5)`) and [ends](https://github.com/NASA-LIS/LISF/blob/f05554b117639b731525d289f7be568daa9d9288/lvt/datastreams/SMAPTB/readSMAPTBobs.F90#L348) just *before* the code that causes the error you reported. The code within the if statement is only run if HDF5 is installed and enabled, which it does not appear to be based on the `configure.lvt` file you provided. These variables therefore surprise the compiler when it skips that if statement.

I recommend installing HDF5 (if you have not done so already) and selecting the HDF5 option when configuring LVT prior to compiling.

@sujayvkumar: Should the code beginning at [line 350](https://github.com/NASA-LIS/LISF/blob/f05554b117639b731525d289f7be568daa9d9288/lvt/datastreams/SMAPTB/readSMAPTBobs.F90#L350) be placed inside the `#if (defined USE_HDF5)` block?

**Comment by rfun** [comment]
Makes sense. I had purposely left hdf5 out for now, as I wanted everything to work with hdf4 first. But this makes sense. I will try it with hdf5 and update this issue. Thanks so much

**Comment by rfun** [comment]
@bmcandr 
Yes, including HDF5 solves this. The only suggestion here would be to ensure that the specific code is run only for hdf5 included installations since the build docs don't list hdf5 as a required dependency but more of an optional thing. I am okay if you would like to close this issue as well.

**Comment by sujayvkumar** [comment]
@bmcandr -I am good with the suggested code change.
