### ISSUE TITLE
Add configure script option for floating point optimization level on Intel compilers

### ISSUE THREAD

**Issue by bmcandr** [NASA-LIS/LISF#626]
This issue is related to the discrepancies in output between SLES11/SLES12 runs identified by Abheera. Using the compiler options `-fp-model precise` or `-fp-model source` resolved these discrepancies with no apparent performance penalty. Sujay and Shugong therefore requested an option be added to the configure script to allow users to set the floating point optimization level with the default level set to `-fp-model precise`.

I took a quick stab at adding this feature on the [`feature/fp-opt-option`](https://github.com/bmcandr/LISF/tree/feature/fp-opt-option) branch in my fork and welcome feedback/improvements. Quick link to compare with the master branch here: https://github.com/NASA-LIS/LISF/compare/master...bmcandr:feature/fp-opt-option

**Comment by emkemp** [comment]
I'm not sure I like an extra configure option just for the Intel compiler.  This could make it difficult for NU-WRF since they support GNU compilers in addition to Intel.  And, at some point we will need to reactivate support for Portland Group compilers.

Can we just set -fp-model precise for positive optimization levels (for Intel) and call it a day?  (This question is directed at Shugong and Sujay.)

**Comment by bmcandr** [comment]
@sujayvkumar @shugongwang, any thoughts on Eric's suggestion to just add `-fp-model precise` for positive optimization levels rather than allowing users to select flag?

**Comment by shugongwang** [comment]
Hello,

I agree with Eric’s suggestion. I think this compiler flag maybe too much technical. We may put it under the hood.

Thanks,

Shugong

**Comment by bmcandr** [comment]
Thanks, Shugong. I'll make the change and open a new pull request.
