### ISSUE TITLE
IMERG Precipitation Reader cut-off

### ISSUE THREAD

**Issue by TimLahmers** [NASA-LIS/LISF#749]
### Bug Description

The IMERG reader is failing due to a file truncation error. Output from LOG File:
[INFO] LIS cycle time: 02/01/2019 03:30:00
 [WARN] Missing IMERG precipitation data:: 
 /discover/nobackup/projects/lis/MET_FORCING/IMERG/Final_V06B//201902/3B-HHR.MS.
 MRG.3IMERG.20190201-

### Steps to Replicate

Relevant lis.config file settings:
IMERG forcing directory:  /discover/nobackup/projects/lis/MET_FORCING/IMERG/Final_V06B/
IMERG product:           'final'
IMERG version:           V06B

**Comment by jerrywegiel** [comment]
Hi Tim, could be you’ve hit the 120-character limit for the path & file name.

v/r
Jerry

Jerry Wegiel, Ph.D.
Principal Investigator, DoD-/IC- components of LIS: https://lis.gsfc.nasa.gov<https://lis.gsfc.nasa.gov/>
NASA/GSFC Hydrological Sciences Laboratory: http://science.gsfc.nasa.gov/earth/hydrology/
SETA Research Scientist Senior Principal (w/ Gov’t NDAs)
101 Nelson Drive
Offutt AFB, NE 68113-1023

240-261-8457 (Mobile)
402-232-7690 (Office)
SIPRNET: ***@***.******@***.***>
***@***.******@***.***>
https://www.linkedin.com/in/jerrywegiel<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.linkedin.com%2Fin%2Fjerrywegiel&data=04%7C01%7Cjerry.w.wegiel%40nasa.gov%7Cfbc39fd973a34d74367f08d8ba4c46a0%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637464184057167215%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=0iwOcs9qqnofB%2Bu5%2FPSDC%2Fy91QzwvGA4IceUV45QyRM%3D&reserved=0>

From: TimLahmers ***@***.***>
Reply-To: NASA-LIS/LISF ***@***.***>
Date: Monday, March 22, 2021 at 6:39 PM
To: NASA-LIS/LISF ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] [NASA-LIS/LISF] IMERG Precipitation Reader cut-off (#749)

Bug Description

The IMERG reader is failing due to a file truncation error. Output from LOG File:
[INFO] LIS cycle time: 02/01/2019 03:30:00
[WARN] Missing IMERG precipitation data::
/discover/nobackup/projects/lis/MET_FORCING/IMERG/Final_V06B//201902/3B-HHR.MS.
MRG.3IMERG.20190201-

Steps to Replicate

Relevant lis.config file settings:
IMERG forcing directory: /discover/nobackup/projects/lis/MET_FORCING/IMERG/Final_V06B/
IMERG product: 'final'
IMERG version: V06B

**Comment by bmcandr** [comment]
This is related to #371 and #533 and will be resolved when #536 is merged.

Workaround for Discover: soft-link to the LIS project directory in your running directory and use that instead of the absolute path.
