### ISSUE TITLE
GCC 10 incompatability

### ISSUE THREAD

**Issue by pratiman-91** [NASA-LIS/LISF#843]
### Bug Description
Unable to compile lis and ldt (did not try with lvt but possibly affected) with GCC 10.
```bash
gfortran -c -pass-exit-codes -ffree-line-length-0 -O2   -fconvert=big-endian -DGFORTRAN -I/opt/lisf_libs/mod/modg/Linux.gfortran.64.mpiuni.default/  -I/opt/lisf_libs//include/ -I/opt/lisf_libs//include/  -I/opt/lisf_libs//include/  -I./ -I../lib/xmrg/ -I../params/VIC/ -I../USAFSI/ ../core/LDT_gfracMod.F90
../core/LDT_gfracMod.F90:478:65:

  478 |                        n, LDT_gfrac_struc(n)%gfrac%value(:,:,k) )
      |                                                                 1
Error: Missing actual argument for argument ‘_formal_8’ at (1)
make: *** [Makefile:108: LDT_gfracMod.o] Error 1

[ERR] Compile failed
```

### Steps to Replicate

Compile LIS and LDT using gcc (Ubuntu 10.3.0-1ubuntu1) 10.3.0 and GNU Fortran (Ubuntu 10.3.0-1ubuntu1) 10.3.0

### Solution

Add flag ```-fallow-argument-mismatch``` to lis and ldt compile scripts.
Additionaly add flag ```-fno-allow-invalid-boz``` for ldt. Due to errors in ```readSMOPSsmObs.F90```
```bash
gfortran -c -pass-exit-codes -ffree-line-length-0 -O2   -fconvert=big-endian -DGFORTRAN -I/opt/lisf_libs/mod/modg/Linux.gfortran.64.mpiuni.default/  -I/opt/lisf_libs//include/ -I/opt/lisf_libs//include/  -I/opt/lisf_libs//include/  -I./ -I../lib/xmrg/ -I../params/VIC/ -I../USAFSI/ ../DAobs/SMOPS/readSMOPSsmObs.F90
```

**Comment by emkemp** [comment]
Thank you for this bug report.  I successfully replicated the LDT compilation error with gfortran 10.1.0 on the NASA DIscover supercomputer running SLES 12.3.  I will investigate further.

**Comment by emkemp** [comment]
Update:  The LDT compilation error also occurs with gfortran 11.1.0.

**Comment by pratiman-91** [comment]
Thanks @emkemp .

Just wanted to update that additional flag for ldt ``` -fno-allow-invalid-boz``` might be ```-fallow-invalid-boz```.  Please check.

**Comment by emkemp** [comment]
Hi @pratiman-91 

I think those extra flags may obscure a more serious bug.

The readgfrac function is implemented in C, and acts as a wrapper for a collection of Fortran subroutines; a particular Fortran subroutine is called based on the first argument (basically, the name of the dataset to be processed).  As I study the C code, I see a mismatch in the argument list.

Fortran is passing this:

call readgfrac( trim(LDT_gfrac_struc(n)%gfrac%source)//char(0),&
                       n, LDT_gfrac_struc(n)%gfrac%value(:,:,k) )

which is *three* arguments: a NULL-terminated string, an integer, and a real array.

The C function expects this:

void FTN(readgfrac)(char *j, int *n,float *array,float *marray,int len)

(The FTN business is just a macro for slightly renaming "readgfrac" based on whatever C naming convention the Fortran compiler expects; we can ignore this.)  The argument list has *five* arguments.  The first three correspond to the arguments passed by Fortran (the * indicates pointers, or passing-by-reference). That leaves two other arguments.

The comments in the C function indicate argument marray (the fourth argument) is optional.  But the compiler is not treating it that way, and I don't know why it should.  A rewrite may be necessary.

@jvgeiger @bmcandr @sujayvkumar  Thoughts?

**Comment by emkemp** [comment]
Update:  I reviewed the underlying Fortran subroutines that can be called by readgfrac.  Only two of them (read_CLSMF25_gfrac and read_SACHTET356_gfrac) accept three arguments, and both of them treat the third argument as optional and never use it.  The remaining subroutines only accept two arguments (an integer and a real array).

I'm of the opinion that the two special Fortran subroutines should be changed to remove the third argument.  Also, the C wrapping code should be changed to reduce the pass-thru argument count to two.  Also, the readgfrac can have the fifth argument removed because it is never used.  Finally, the readgfrac function does not handle the case of an undefined greenness fraction dataset, so I will add some code for that as well.

**Comment by karsenau** [comment]
Hi @emkemp:

Thank you for taking a closer look at these Fortran routines and the related C routines. If these are the only two Fortran routines for "gfrac" affected, I would agree with the approach that you outlined here.

Thanks!

**Comment by pratiman-91** [comment]
Thank you @emkemp for such details. @karsenau I would like to add that there are multiple (5-7) instances in both LDT and LIS where I found the same compilation problem. Meaning, there could be multiple files that need to be verified.

**Comment by karsenau** [comment]
Thanks for reporting that @pratiman-91.  If you have a list of when you encounter that issue, we would be happy to check and make any necessary updates.

**Comment by emkemp** [comment]
Update:  The error reported by the compiler seems to be triggered by invocations of readgfrac with different numbers of arguments, and occurs *before* the C code is compiled.  

I see the same error with calls to read_FLake_lakedepth, with different number of arguments.  In that case, the routine is written in Fortran (no C wrapping at all), but is not enclosed in a Fortran module -- thus, optional arguments are probably illegal, since the compiler can't check them without an interface block.

I'm guessing these recent gfortran versions are adding argument checks on their own, informing us of these problems.

**Comment by emkemp** [comment]
Okay, my LDT revisions have expanded to four major directions:

* Update gfrac and lai/sai Fortran read codes to use the same number of arguments (2).
* Update the gfrac and lai/sai C codes to remove unnecessary arguments.
* Update FLAKE code to ove read_FLake_lakedepth into FLAKE_paramsMode, allowing use of optional argument.
* Modified readSMOPSsmObs to move usage of binary integer constants to DATA statements (standard Fortran does not allow for use with PARAMETERs, though ifort permits it).

...plus minor editorial changes.

The code compiles with gfortran 11.1.0, but further code clean-up is necessary; plus compilations with older GNU compilers and with Intel.  Also, I don't think I can actually run with gfortran 11.1.0 without recompiling all the external libraries.

An experimental branch is available for view at https://github.com/emkemp/LISF/tree/fix/ldt_arg_lists.  No pull request yet, it's not mature enough.

**Comment by pratiman-91** [comment]
### List of affected files in LIS:
1. core/LIS_albedoMod.F90
2. core/LIS_emissMod.F90
3. core/LIS_vegDataMod.F90
4. surfacemodels/land/rdhm.3.5.6/sachtet/htet_fland1.f
5. surfacemodels/land/vic.4.1.1/vic411_f2t.F90
6. surfacemodels/land/vic.4.1.2/vic412_f2t.F90

### List of affected files in LDT:
1. core/LDT_gfracMod.F90
2. params/FLAKE/FLAKE_parmsMod.F90
3. core/LDT_laisaiMod.F90
4. DAobs/SMOPS/readSMOPSsmObs.F90

**Comment by karsenau** [comment]
Thank you so much, @pratiman-91, for your help in compiling this list of routines affected with GCC 10.

**Comment by emkemp** [comment]
I just submitted pull request #850 to address the problems with LDT.  Fixes for LIS (and LVT?) will be handled separately.

**Comment by emkemp** [comment]
I replaced pull request #850 with #851, which targets the support/lisf-public-7.3 branch.

**Comment by emkemp** [comment]
I've started reviewing LIS proper.  First problem is the use of readalbedo in LIS_albedoMod.F90.

The call signature in C is:

void FTN(readalbedo)(char *j, int *n, void *time1, void *time2, float *array1, float *array2,int len)

with len never being used.  The calls on the Fortran side are inconsistent.  I see:

call readalbedo(trim(LIS_rc%usealbedomap(n))//char(0),&
                  n,wt1,wt1,LIS_alb(n)%albsf1,LIS_alb(n)%albsf2)

which is mostly correct.  But then I see:

             call readalbedo(trim(LIS_rc%usealbedomap(n))//char(0),&
                  n,t1,value1)
             call readalbedo(trim(LIS_rc%usealbedomap(n))//char(0),&
                  n,t2,value2)

That's not correct.  I will fix.

**Comment by emkemp** [comment]
Some more info:  The only Fortran routine called under-the-hood by readalbeo is read_ALMPIIIalbedo, which has a call signature of:

subroutine read_ALMIPIIalbedo(n, wt1,wt2,array1,array2)

where wt1 and wt2 are reals that represent weights.  But the two "bad" readalbedo calls are passing time indexes (t1 and t2), which are recalculated internally by read_ALMIPIIalbedo.

So, I am going to change the calls to all use wt1 and wt2 as reals.

**Comment by emkemp** [comment]
Another problem is the reading of LAI data in LIS.  Unfortunately, this seems to be very broken.

The C function readlai uses this interface when calling Fortran:

current->func(n,time1,time2,array1,array2)

where the arguments are:

int *n, void *time1, void *time2, float *array1, float *array2

However, the underlying Fortran routines have very different argument lists:

subroutine read_ALMIPIIlai(n, wt1,wt2,array1,array2)
  integer, intent(in) :: n
  real                :: wt1
  real                :: wt2
  real, intent(inout) :: array1(LIS_rc%ntiles(n))
  real, intent(inout) :: array2(LIS_rc%ntiles(n))

subroutine read_MODISlai(n, time1, array)
  integer, intent(in) :: n
  type(ESMF_Time)     :: time1
  real, intent(inout) :: array(LIS_rc%ntiles(n))

subroutine read_MODIS_RT_lai(n, forward_search, array, file_time_stamp)
  integer, intent(in)               :: n
  logical, intent(in)               :: forward_search
  type(ESMF_Time), intent (out)     :: file_time_stamp
  real, intent(inout)               :: array(LIS_rc%ntiles(n))

The third call at least is probably not working correctly, since readlai will pass a float* for the file_time_stamp.  In any case, the calls to readlai will not compile with gfortran 10+ because the corresponding call signatures vary in LIS_vegDataMod.F90:

call readlai(trim(LIS_rc%uselaimap(n))//char(0),n,&
                  wt1,wt2,LIS_lai(n)%lai1,LIS_lai(n)%time1)

...

             forward_search=.false.
             call readlai(trim(LIS_rc%uselaimap(n))//char(0),n,&
                  forward_search,LIS_lai(n)%lai1,LIS_lai(n)%time1)

             forward_search=.true.
             call readlai(trim(LIS_rc%uselaimap(n))//char(0),n,&
                  forward_search,LIS_lai(n)%lai2,LIS_lai(n)%time2)

I think this requires a more serious redesign, perhaps using more modern Fortran constructs, e.g., Fortran 90 interfaces.

**Comment by emkemp** [comment]
A correction:  The readlai calls involving 'forward search' are disabled by a #if 0 preprocessor statement.  It appears then that the 

call readlai(trim(LIS_rc%uselaimap(n))//char(0),n,wt1,wt2,LIS_lai(n)%lai1,LIS_lai(n)%time1)

signature is the desired one, at least for ALMIPII data.

**Comment by dmocko** [comment]
Hi @emkemp 

I have been working on a fix to the LIS MODIS LAI RT code - see Issue #394 

I have been meaning to come back to it.  Not sure if I will be able to in the next ~week, but can bump the priority.

David

**Comment by emkemp** [comment]
Thanks @dmocko 

SInce the MODIS_RT reader is broken (and I concur it is, based on the argument list mismatch), I think the default.cfg should be changed to disable MODIS real-time by default.

@jvgeiger @sujayvkumar  Thoughts?

**Comment by dmocko** [comment]
Yes, - it should be disabled, until I have a fix to update to Collection 6.

The Collection 5 data is no longer available, I believe, and the current code (if it worked) would need this data to be pre-processed anyway by the MRT tool.

**Comment by emkemp** [comment]
Okay, I'll add that to an upcoming pull request.

**Comment by emkemp** [comment]
Whelp, GFORTRAN 10+ just found a bug in RDHM 3.5.6.

The source code in lis/surfacemodels/land/rdhm.3.5.6/sachtet is column-limited Fortran 77.  In htet_fland1.f, there is a call to pehman_ohd that extends past 72 columns, and is truncated by the compiler (line 647).  A different call further up is not truncated (different indentation), and the compiler noticed a different argument list between the two calls.

Simply changing the indentation by 2 columns fixes this bug.  I do wonder what affect this has on any science runs made with this code...

**Comment by emkemp** [comment]
I just opened pull request #854 to fix problems with LIS 7.3.

**Comment by emkemp** [comment]
I just opened pull request #855 to fix the compilation problems in LVT 7.3.  Fortunately this is small, just involving binary integer constants.

**Comment by bmcandr** [comment]
Looks like #851, #854, and #855 addressed the GCC10 compile errors. Can we close out this issue?

**Comment by emkemp** [comment]
I have no objection to closing this issue.
